run:
  deadline: 5m
  concurrency: 1
  tests: true
  skip-files:
    - ".*_test.go"
linters:
  enable-all: true
  disable:
    # Too restrictive
    - depguard
    - exhaustive
    - exhaustruct
    - exhaustivestruct
    - goerr113
    
    # Too opinionated
    - lll
    - gomnd 
    - varnamelen 
issues:
  max-per-linter: 0
  max-same-issues: 0
