name: Go package

on: [push]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
    

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.57

      - name: Install Dependencies
        run: go get .

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -o service main.go